source/common/objects/C52_MongoSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>C52 Mongo Settings</description>

	<fields>
        <fullName>Database__c</fullName>
        <defaultValue>&quot;heroku_w830mlvd&quot;</defaultValue>
        <description>the database name</description>
        <label>Mongodb Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TokenType__c</fullName>
        <defaultValue>&quot;bearer&quot;</defaultValue>
        <description>the token type</description>
        <label>Token Type</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>the auth token</description>
        <label>Auth Token</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>C52 Mongo Settings</label>
</CustomObject>

source/common/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>IncludeForWebMobile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Includes the campaign in the sync data that is used for web and mobile sign-ups</description>
        <label>Include for Web &amp; Mobile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True = file has been processed.  False = will be picked up in next iteration of the processing job.</description>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

source/common/classes/tests/ObjectsHelper.cls
@isTest
/*
* Helper class to populate objects used in test methods.
*/
public class ObjectsHelper {
	/*
	* helper method to populate a Campaign object
	*/
	public static Campaign getCampaign(string name, Boolean includeWeb, Boolean processed, Campaign parentCampaign, string recordTypeName) {
		Campaign camp = new Campaign();
		camp.Name = name;
		camp.IncludeForWebMobile__c = includeWeb;
		camp.Processed__c = processed;
		camp.Parent = parentCampaign;
		camp.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
		
		return camp;
	}
	
	
	/*
	* helper method to populate a GW_Volunteers__Volunteer_Job__c
	*/
	public static GW_Volunteers__Volunteer_Job__c getGWVolunteersVolunteerJob(string name, ID campaignId, Boolean processed, Boolean includeWeb) {
		GW_Volunteers__Volunteer_Job__c gwvvJob = new GW_Volunteers__Volunteer_Job__c();
		gwvvJob.Name = name;
		gwvvJob.GW_Volunteers__Campaign__c = campaignId;
		gwvvJob.Processed__c = processed;
		gwvvJob.GW_Volunteers__Display_on_Website__c = includeWeb;
		
		return gwvvJob;
	}
	
	/*
	 * helper method to populate C52_MongoSettings__c (customSettings)
	*/
	public static C52_MongoSettings__c getMongoSettings(string dbName, string tokenType, string token) {
		C52_MongoSettings__c settings = new C52_MongoSettings__c(
			Token__c = token,
			TokenType__c = tokenType,
			Database__c = dbName,
			Name = Constants.MONGO_SETTINGS_NAME
		);
		
		return settings;
	} 
}