source/common/objects/C52_MongoSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>C52 Mongo Settings</description>

	<fields>
        <fullName>Database__c</fullName>
        <defaultValue>&quot;heroku_w830mlvd&quot;</defaultValue>
        <description>the database name</description>
        <label>Mongodb Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TokenType__c</fullName>
        <defaultValue>&quot;bearer&quot;</defaultValue>
        <description>the token type</description>
        <label>Token Type</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>the auth token</description>
        <label>Auth Token</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>C52 Mongo Settings</label>
</CustomObject>

source/common/classes/common/Settings.cls
public with sharing class Settings {
	/*
	 * Description:
	 *	Gets the monogo Database name
	 * Returns:
	 *	String - the database name
	*/
	public static String getMongoDBName() {
		C52_MongoSettings__c mongoSettings = Settings.getMongoSettingsValues();
		return mongoSettings == null ? null : mongoSettings.Database__c;
	}
	
	public static String getMongoTokenType() {
		C52_MongoSettings__c mongoSettings = Settings.getMongoSettingsValues();
		return mongoSettings == null ? null : mongoSettings.TokenType__c;
	}
	
	public static String getMongoToken() {
		C52_MongoSettings__c mongoSettings = Settings.getMongoSettingsValues();
		return mongoSettings == null ? null : mongoSettings.Token__c;
	}
	
	/*
	 * Description:
	 *	gets the MongoSettings by name
	 * Returns:
	 *	C52_MongoSettings__c - the settings record.
	*/
	private static C52_MongoSettings__c getMongoSettingsValues() {
		return C52_MongoSettings__c.GetValues(Constants.MONGO_SETTINGS_NAME);
	}
}