source/common/objects/C52_MongoSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>C52 Mongo Settings</description>

	<fields>
        <fullName>Database__c</fullName>
        <defaultValue>&quot;heroku_w830mlvd&quot;</defaultValue>
        <description>the database name</description>
        <label>Mongodb Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>C52 Mongo Settings</label>
</CustomObject>

source/common/classes/install/AppSettingsInstaller.cls
public with sharing class AppSettingsInstaller implements IInstallable {
	public void install(InstallContext context) {
		if(context == null || context.previousVersion() == null) {
			initialInstall(null);
		}
	}
	
	public void initialInstall(String username) {
		Savepoint savepoint;
		
		try {
			savepoint = Database.setSavepoint();
			C52_MongoSettings__c mongoSettings;
			
			if(username == null || username == '') {
				mongoSettings = new C52_MongoSettings__c(
					Name = Constants.MONGO_SETTINGS_NAME,
					Database__c = 'heroku_w830mlvd'
				);
			}
			
			insert mongoSettings;
			
		} catch(Exception ex) {
			Database.rollback(savepoint);
			throw ex;
		}
	}
}